### ISSUE TITLE
Apostrophe not parsed correctly

### ISSUE THREAD

**Issue by falcondai** [brianc/jade-mode#20]
example:
```stylus
p= 'i should be parsed as string delimiter'
p i shouldn't be parsed as the beginning of a string 
```

i am seeing the second line being parsed incorrectly

**Comment by tjefferson08** [comment]
+1

**Comment by tjefferson08** [comment]
Looks like it's due to the rendering order of font-lock (?). My guess is the syntax table has the single quote  (`'`) in it (from a parent mode like sws-mode or fundamental-mode). Even if you add a keyword search which isolates the block of text with the `'` in it, the fact that quotes are actual syntax table entries gives them higher priority (I can't actually find this rendering order documented anywhere, but experimentation manifests this phenomenon). I'm working on a fix which will remove the quote chars from the syntax table and **instead** use [search-based fontification](http://www.gnu.org/software/emacs/manual/html_node/elisp/Search_002dbased-Fontification.html) to highlight strings (only where it's jade-appropriate). For reference: here's the documentation for [syntactic fontification](http://www.gnu.org/software/emacs/manual/html_node/elisp/Syntactic-Font-Lock.html#Syntactic-Font-Lock)
