### ISSUE TITLE
recent melpa update broke single-quoted strings

### ISSUE THREAD

**Issue by chillum** [brianc/jade-mode#37]
I have:

```jade
doctype html
html
  head
    meta(charset='utf-8')
    link(rel='stylesheet', type='text/css', href='main.css')
```

It used to highlight OK, but with version 20150313.812 from MELPA the highlighting does not work. Double-quoted strings still work:

```jade
doctype html
html
  head
    meta(charset="utf-8")
    link(rel="stylesheet", type="text/css", href="main.css")
```

**Comment by tjefferson08** [comment]
Hey, thanks for noticing! I quietly sacrificed this highlighting feature in order to fix issue #20. 

The details: I took single quotes out of the syntax class for quote characters, so they no longer automatically highlight as strings, you have to go find them and highlight them with other search/highlight rules. I left double quotes alone, although it could be argued that they should operate in the same manner (it's just that nobody uses double quote literals in their markup!).

I'd really like to get the whole paren regions to highlight as JS, but I could do an interim fix just for string literals.

**Comment by chillum** [comment]
Recent update (20150321.825) broke it again. Take a look:
![Screenshot](https://cloud.githubusercontent.com/assets/6885179/6798400/4ec82bc2-d215-11e4-9393-b1ce7113045d.png)

**Comment by tjefferson08** [comment]
Thanks very much for reporting that here. I can't say for sure, but it looks like this is breaking in the middle of your file, maybe (hopefully!) on the line opening with the pipe `|`.

There is a PR open right now which fixes the pipe issue! I'll go merge it :) Please update this issue if the update doesn't solve the problem.
